name: EventService Docker Build

on:
  pull_request:
    branches: 
    - main 
    paths:
    - "EventService/**"
  
  # Allows to run the workflow manually from actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3         
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DH_USERNAME }}/eventservice:latest -f EventService/Dockerfile ./EventService
