name: Deploy NuGet Package

on: 
  push:
    tags:
    - 'v*'


env:
  PROJECT_PATH: MessageBusEvents/MessageBusEvents.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.*'
      
    - name: Restore package
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    # Get version of NuGet package from tag
    - name: Get version
      id: version
      uses: battila7/get-version-action@v2

    - name: Pack project
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: Push package
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}