name: Update Auth Docker image tag in configuration repo

on:
  workflow_run:
    workflows: ["AuthService Docker Deploy"]
    branches: main
    types:
      - completed
    
jobs:
  update-image-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          # Repository name with owner. For example, actions/checkout
          repository: 'omarade/EventEase-IAC'  
          token: ${{ secrets.GH_TOKEN }} 

      - name: Update Auth yaml file in place
        # You may pin to the exact commit or the version.
        uses: loveholidays/gitops-action-yaml-updater@v1.0.0
        with:
          # TYPE of the new value to be updated
          mode: IMAGE_TAG
          # Name of the container
          container-name: authservice
          # Path to the yaml file
          filepath: K8S/auth-depl.yaml
          # Tag value for the new image
          new-image-tag: ${{ github.sha }}

      - name: Add & Commit
        # You may pin to the exact commit or the version.
        uses: EndBug/add-and-commit@v9.1.3
        with:
          # Arguments for the git add command
          add: "*"
          # The message for the commit
          message: Update authservice docker image version
          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (more info in the README)
          push: true
          # The token used to make requests to the GitHub API. It's NOT used to make commits and should not be changed.
          github_token: ${{ secrets.GH_TOKEN }}
      
      - name: Pull changes again (to make sure local changes are up-to-date)
        run: |
          echo ${{ github.sha }}
          git pull origin main

      - name: GitHub Push
        # You may pin to the exact commit or the version.
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
          repository: 'omarade/EventEase-IAC'
          # Destination branch to push changes
          branch: main
          # Determines if force push is used
          force: false
