name: UserService Docker Build & Test

on:
  pull_request:
    branches: 
    - main 
    paths:
    - "UserService/**"
  
  # Allows to run the workflow manually from actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3         
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DH_USERNAME }}/userservice:latest -f UserService/Dockerfile ./UserService

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Unit Test UserService
      run: dotnet test ./UserService.UnitTests    
    - name: Integration Test User Service
      run: dotnet test ./UserService.IntegrationTests
